name: Publish to GitHub Pages when a branch is merged

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
        
      - name: Publish generated content to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
